---
- name: assert | Test if supported Linux version
  ansible.builtin.assert:
    that:
      - ansible_distribution in [ 'OracleLinux' ]
      - ansible_distribution_major_version is version(8, '==')
    quiet: true
